/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmallBoatsRouteImport } from './routes/small-boats'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseboatsIndexRouteImport } from './routes/houseboats.index'
import { Route as SmallBoatsSlugRouteImport } from './routes/small-boats_.$slug'
import { Route as HouseboatsSenatorRouteImport } from './routes/houseboats.senator'
import { Route as HouseboatsQueenIiRouteImport } from './routes/houseboats.queen-ii'
import { Route as HouseboatsQueenIRouteImport } from './routes/houseboats.queen-i'
import { Route as HouseboatsQueenRouteImport } from './routes/houseboats.queen'

const SmallBoatsRoute = SmallBoatsRouteImport.update({
  id: '/small-boats',
  path: '/small-boats',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsIndexRoute = HouseboatsIndexRouteImport.update({
  id: '/houseboats/',
  path: '/houseboats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallBoatsSlugRoute = SmallBoatsSlugRouteImport.update({
  id: '/small-boats_/$slug',
  path: '/small-boats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsSenatorRoute = HouseboatsSenatorRouteImport.update({
  id: '/houseboats/senator',
  path: '/houseboats/senator',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIiRoute = HouseboatsQueenIiRouteImport.update({
  id: '/houseboats/queen-ii',
  path: '/houseboats/queen-ii',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIRoute = HouseboatsQueenIRouteImport.update({
  id: '/houseboats/queen-i',
  path: '/houseboats/queen-i',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenRoute = HouseboatsQueenRouteImport.update({
  id: '/houseboats/queen',
  path: '/houseboats/queen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/small-boats': typeof SmallBoatsRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats/$slug': typeof SmallBoatsSlugRoute
  '/houseboats/': typeof HouseboatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/small-boats': typeof SmallBoatsRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats/$slug': typeof SmallBoatsSlugRoute
  '/houseboats': typeof HouseboatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directions': typeof DirectionsRoute
  '/small-boats': typeof SmallBoatsRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats_/$slug': typeof SmallBoatsSlugRoute
  '/houseboats/': typeof HouseboatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directions'
    | '/small-boats'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats/$slug'
    | '/houseboats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directions'
    | '/small-boats'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats/$slug'
    | '/houseboats'
  id:
    | '__root__'
    | '/'
    | '/directions'
    | '/small-boats'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats_/$slug'
    | '/houseboats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectionsRoute: typeof DirectionsRoute
  SmallBoatsRoute: typeof SmallBoatsRoute
  HouseboatsQueenRoute: typeof HouseboatsQueenRoute
  HouseboatsQueenIRoute: typeof HouseboatsQueenIRoute
  HouseboatsQueenIiRoute: typeof HouseboatsQueenIiRoute
  HouseboatsSenatorRoute: typeof HouseboatsSenatorRoute
  SmallBoatsSlugRoute: typeof SmallBoatsSlugRoute
  HouseboatsIndexRoute: typeof HouseboatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/small-boats': {
      id: '/small-boats'
      path: '/small-boats'
      fullPath: '/small-boats'
      preLoaderRoute: typeof SmallBoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/': {
      id: '/houseboats/'
      path: '/houseboats'
      fullPath: '/houseboats/'
      preLoaderRoute: typeof HouseboatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-boats_/$slug': {
      id: '/small-boats_/$slug'
      path: '/small-boats/$slug'
      fullPath: '/small-boats/$slug'
      preLoaderRoute: typeof SmallBoatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/senator': {
      id: '/houseboats/senator'
      path: '/houseboats/senator'
      fullPath: '/houseboats/senator'
      preLoaderRoute: typeof HouseboatsSenatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-ii': {
      id: '/houseboats/queen-ii'
      path: '/houseboats/queen-ii'
      fullPath: '/houseboats/queen-ii'
      preLoaderRoute: typeof HouseboatsQueenIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-i': {
      id: '/houseboats/queen-i'
      path: '/houseboats/queen-i'
      fullPath: '/houseboats/queen-i'
      preLoaderRoute: typeof HouseboatsQueenIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen': {
      id: '/houseboats/queen'
      path: '/houseboats/queen'
      fullPath: '/houseboats/queen'
      preLoaderRoute: typeof HouseboatsQueenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectionsRoute: DirectionsRoute,
  SmallBoatsRoute: SmallBoatsRoute,
  HouseboatsQueenRoute: HouseboatsQueenRoute,
  HouseboatsQueenIRoute: HouseboatsQueenIRoute,
  HouseboatsQueenIiRoute: HouseboatsQueenIiRoute,
  HouseboatsSenatorRoute: HouseboatsSenatorRoute,
  SmallBoatsSlugRoute: SmallBoatsSlugRoute,
  HouseboatsIndexRoute: HouseboatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
