/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseboatsSenatorRouteImport } from './routes/houseboats.senator'
import { Route as HouseboatsQueenIiRouteImport } from './routes/houseboats.queen-ii'
import { Route as HouseboatsQueenIRouteImport } from './routes/houseboats.queen-i'
import { Route as HouseboatsQueenRouteImport } from './routes/houseboats.queen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsSenatorRoute = HouseboatsSenatorRouteImport.update({
  id: '/houseboats/senator',
  path: '/houseboats/senator',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIiRoute = HouseboatsQueenIiRouteImport.update({
  id: '/houseboats/queen-ii',
  path: '/houseboats/queen-ii',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIRoute = HouseboatsQueenIRouteImport.update({
  id: '/houseboats/queen-i',
  path: '/houseboats/queen-i',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenRoute = HouseboatsQueenRouteImport.update({
  id: '/houseboats/queen',
  path: '/houseboats/queen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
  id:
    | '__root__'
    | '/'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseboatsQueenRoute: typeof HouseboatsQueenRoute
  HouseboatsQueenIRoute: typeof HouseboatsQueenIRoute
  HouseboatsQueenIiRoute: typeof HouseboatsQueenIiRoute
  HouseboatsSenatorRoute: typeof HouseboatsSenatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/senator': {
      id: '/houseboats/senator'
      path: '/houseboats/senator'
      fullPath: '/houseboats/senator'
      preLoaderRoute: typeof HouseboatsSenatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-ii': {
      id: '/houseboats/queen-ii'
      path: '/houseboats/queen-ii'
      fullPath: '/houseboats/queen-ii'
      preLoaderRoute: typeof HouseboatsQueenIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-i': {
      id: '/houseboats/queen-i'
      path: '/houseboats/queen-i'
      fullPath: '/houseboats/queen-i'
      preLoaderRoute: typeof HouseboatsQueenIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen': {
      id: '/houseboats/queen'
      path: '/houseboats/queen'
      fullPath: '/houseboats/queen'
      preLoaderRoute: typeof HouseboatsQueenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseboatsQueenRoute: HouseboatsQueenRoute,
  HouseboatsQueenIRoute: HouseboatsQueenIRoute,
  HouseboatsQueenIiRoute: HouseboatsQueenIiRoute,
  HouseboatsSenatorRoute: HouseboatsSenatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
