/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmallBoatsRouteImport } from './routes/small-boats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShastaVsLakePowellRouteImport } from './routes/shasta-vs-lake-powell'
import { Route as ShastaLakeRouteImport } from './routes/shasta-lake'
import { Route as ProShopRouteImport } from './routes/pro-shop'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MoorageRouteImport } from './routes/moorage'
import { Route as GuestInfoRouteImport } from './routes/guest-info'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploringShastaLakeRouteImport } from './routes/exploring-shasta-lake'
import { Route as EmploymentRouteImport } from './routes/employment'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabinsRouteImport } from './routes/cabins'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseboatsIndexRouteImport } from './routes/houseboats.index'
import { Route as SmallBoatsSlugRouteImport } from './routes/small-boats_.$slug'
import { Route as HouseboatsSenatorRouteImport } from './routes/houseboats.senator'
import { Route as HouseboatsQueenIiRouteImport } from './routes/houseboats.queen-ii'
import { Route as HouseboatsQueenIRouteImport } from './routes/houseboats.queen-i'
import { Route as HouseboatsQueenRouteImport } from './routes/houseboats.queen'
import { Route as HouseboatsPolicyRouteImport } from './routes/houseboats.policy'
import { Route as CompareQueensRouteImport } from './routes/compare.queens'
import { Route as CabinsPolicyRouteImport } from './routes/cabins_.policy'
import { Route as AboutHistoryRouteImport } from './routes/about.history'
import { Route as ApiPublicGoogleReviewsRouteImport } from './routes/api/public/google-reviews'
import { Route as ApiPublicHooksRefreshReviewsRouteImport } from './routes/api/public/hooks/refresh-reviews'

const SmallBoatsRoute = SmallBoatsRouteImport.update({
  id: '/small-boats',
  path: '/small-boats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShastaVsLakePowellRoute = ShastaVsLakePowellRouteImport.update({
  id: '/shasta-vs-lake-powell',
  path: '/shasta-vs-lake-powell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShastaLakeRoute = ShastaLakeRouteImport.update({
  id: '/shasta-lake',
  path: '/shasta-lake',
  getParentRoute: () => rootRouteImport,
} as any)
const ProShopRoute = ProShopRouteImport.update({
  id: '/pro-shop',
  path: '/pro-shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MoorageRoute = MoorageRouteImport.update({
  id: '/moorage',
  path: '/moorage',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestInfoRoute = GuestInfoRouteImport.update({
  id: '/guest-info',
  path: '/guest-info',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploringShastaLakeRoute = ExploringShastaLakeRouteImport.update({
  id: '/exploring-shasta-lake',
  path: '/exploring-shasta-lake',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploymentRoute = EmploymentRouteImport.update({
  id: '/employment',
  path: '/employment',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsRoute = CabinsRouteImport.update({
  id: '/cabins',
  path: '/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsIndexRoute = HouseboatsIndexRouteImport.update({
  id: '/houseboats/',
  path: '/houseboats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallBoatsSlugRoute = SmallBoatsSlugRouteImport.update({
  id: '/small-boats_/$slug',
  path: '/small-boats/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsSenatorRoute = HouseboatsSenatorRouteImport.update({
  id: '/houseboats/senator',
  path: '/houseboats/senator',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIiRoute = HouseboatsQueenIiRouteImport.update({
  id: '/houseboats/queen-ii',
  path: '/houseboats/queen-ii',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenIRoute = HouseboatsQueenIRouteImport.update({
  id: '/houseboats/queen-i',
  path: '/houseboats/queen-i',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsQueenRoute = HouseboatsQueenRouteImport.update({
  id: '/houseboats/queen',
  path: '/houseboats/queen',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseboatsPolicyRoute = HouseboatsPolicyRouteImport.update({
  id: '/houseboats/policy',
  path: '/houseboats/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareQueensRoute = CompareQueensRouteImport.update({
  id: '/compare/queens',
  path: '/compare/queens',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsPolicyRoute = CabinsPolicyRouteImport.update({
  id: '/cabins_/policy',
  path: '/cabins/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryRoute = AboutHistoryRouteImport.update({
  id: '/about/history',
  path: '/about/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleReviewsRoute = ApiPublicGoogleReviewsRouteImport.update({
  id: '/api/public/google-reviews',
  path: '/api/public/google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshReviewsRoute =
  ApiPublicHooksRefreshReviewsRouteImport.update({
    id: '/api/public/hooks/refresh-reviews',
    path: '/api/public/hooks/refresh-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/directions': typeof DirectionsRoute
  '/employment': typeof EmploymentRoute
  '/exploring-shasta-lake': typeof ExploringShastaLakeRoute
  '/faq': typeof FaqRoute
  '/guest-info': typeof GuestInfoRoute
  '/moorage': typeof MoorageRoute
  '/planning': typeof PlanningRoute
  '/pro-shop': typeof ProShopRoute
  '/shasta-lake': typeof ShastaLakeRoute
  '/shasta-vs-lake-powell': typeof ShastaVsLakePowellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-boats': typeof SmallBoatsRoute
  '/about/history': typeof AboutHistoryRoute
  '/cabins/policy': typeof CabinsPolicyRoute
  '/compare/queens': typeof CompareQueensRoute
  '/houseboats/policy': typeof HouseboatsPolicyRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats/$slug': typeof SmallBoatsSlugRoute
  '/houseboats/': typeof HouseboatsIndexRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/hooks/refresh-reviews': typeof ApiPublicHooksRefreshReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/directions': typeof DirectionsRoute
  '/employment': typeof EmploymentRoute
  '/exploring-shasta-lake': typeof ExploringShastaLakeRoute
  '/faq': typeof FaqRoute
  '/guest-info': typeof GuestInfoRoute
  '/moorage': typeof MoorageRoute
  '/planning': typeof PlanningRoute
  '/pro-shop': typeof ProShopRoute
  '/shasta-lake': typeof ShastaLakeRoute
  '/shasta-vs-lake-powell': typeof ShastaVsLakePowellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-boats': typeof SmallBoatsRoute
  '/about/history': typeof AboutHistoryRoute
  '/cabins/policy': typeof CabinsPolicyRoute
  '/compare/queens': typeof CompareQueensRoute
  '/houseboats/policy': typeof HouseboatsPolicyRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats/$slug': typeof SmallBoatsSlugRoute
  '/houseboats': typeof HouseboatsIndexRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/hooks/refresh-reviews': typeof ApiPublicHooksRefreshReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cabins': typeof CabinsRoute
  '/contact': typeof ContactRoute
  '/directions': typeof DirectionsRoute
  '/employment': typeof EmploymentRoute
  '/exploring-shasta-lake': typeof ExploringShastaLakeRoute
  '/faq': typeof FaqRoute
  '/guest-info': typeof GuestInfoRoute
  '/moorage': typeof MoorageRoute
  '/planning': typeof PlanningRoute
  '/pro-shop': typeof ProShopRoute
  '/shasta-lake': typeof ShastaLakeRoute
  '/shasta-vs-lake-powell': typeof ShastaVsLakePowellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/small-boats': typeof SmallBoatsRoute
  '/about/history': typeof AboutHistoryRoute
  '/cabins_/policy': typeof CabinsPolicyRoute
  '/compare/queens': typeof CompareQueensRoute
  '/houseboats/policy': typeof HouseboatsPolicyRoute
  '/houseboats/queen': typeof HouseboatsQueenRoute
  '/houseboats/queen-i': typeof HouseboatsQueenIRoute
  '/houseboats/queen-ii': typeof HouseboatsQueenIiRoute
  '/houseboats/senator': typeof HouseboatsSenatorRoute
  '/small-boats_/$slug': typeof SmallBoatsSlugRoute
  '/houseboats/': typeof HouseboatsIndexRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/hooks/refresh-reviews': typeof ApiPublicHooksRefreshReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cabins'
    | '/contact'
    | '/directions'
    | '/employment'
    | '/exploring-shasta-lake'
    | '/faq'
    | '/guest-info'
    | '/moorage'
    | '/planning'
    | '/pro-shop'
    | '/shasta-lake'
    | '/shasta-vs-lake-powell'
    | '/sitemap.xml'
    | '/small-boats'
    | '/about/history'
    | '/cabins/policy'
    | '/compare/queens'
    | '/houseboats/policy'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats/$slug'
    | '/houseboats/'
    | '/api/public/google-reviews'
    | '/api/public/hooks/refresh-reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cabins'
    | '/contact'
    | '/directions'
    | '/employment'
    | '/exploring-shasta-lake'
    | '/faq'
    | '/guest-info'
    | '/moorage'
    | '/planning'
    | '/pro-shop'
    | '/shasta-lake'
    | '/shasta-vs-lake-powell'
    | '/sitemap.xml'
    | '/small-boats'
    | '/about/history'
    | '/cabins/policy'
    | '/compare/queens'
    | '/houseboats/policy'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats/$slug'
    | '/houseboats'
    | '/api/public/google-reviews'
    | '/api/public/hooks/refresh-reviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cabins'
    | '/contact'
    | '/directions'
    | '/employment'
    | '/exploring-shasta-lake'
    | '/faq'
    | '/guest-info'
    | '/moorage'
    | '/planning'
    | '/pro-shop'
    | '/shasta-lake'
    | '/shasta-vs-lake-powell'
    | '/sitemap.xml'
    | '/small-boats'
    | '/about/history'
    | '/cabins_/policy'
    | '/compare/queens'
    | '/houseboats/policy'
    | '/houseboats/queen'
    | '/houseboats/queen-i'
    | '/houseboats/queen-ii'
    | '/houseboats/senator'
    | '/small-boats_/$slug'
    | '/houseboats/'
    | '/api/public/google-reviews'
    | '/api/public/hooks/refresh-reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CabinsRoute: typeof CabinsRoute
  ContactRoute: typeof ContactRoute
  DirectionsRoute: typeof DirectionsRoute
  EmploymentRoute: typeof EmploymentRoute
  ExploringShastaLakeRoute: typeof ExploringShastaLakeRoute
  FaqRoute: typeof FaqRoute
  GuestInfoRoute: typeof GuestInfoRoute
  MoorageRoute: typeof MoorageRoute
  PlanningRoute: typeof PlanningRoute
  ProShopRoute: typeof ProShopRoute
  ShastaLakeRoute: typeof ShastaLakeRoute
  ShastaVsLakePowellRoute: typeof ShastaVsLakePowellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmallBoatsRoute: typeof SmallBoatsRoute
  AboutHistoryRoute: typeof AboutHistoryRoute
  CabinsPolicyRoute: typeof CabinsPolicyRoute
  CompareQueensRoute: typeof CompareQueensRoute
  HouseboatsPolicyRoute: typeof HouseboatsPolicyRoute
  HouseboatsQueenRoute: typeof HouseboatsQueenRoute
  HouseboatsQueenIRoute: typeof HouseboatsQueenIRoute
  HouseboatsQueenIiRoute: typeof HouseboatsQueenIiRoute
  HouseboatsSenatorRoute: typeof HouseboatsSenatorRoute
  SmallBoatsSlugRoute: typeof SmallBoatsSlugRoute
  HouseboatsIndexRoute: typeof HouseboatsIndexRoute
  ApiPublicGoogleReviewsRoute: typeof ApiPublicGoogleReviewsRoute
  ApiPublicHooksRefreshReviewsRoute: typeof ApiPublicHooksRefreshReviewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/small-boats': {
      id: '/small-boats'
      path: '/small-boats'
      fullPath: '/small-boats'
      preLoaderRoute: typeof SmallBoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shasta-vs-lake-powell': {
      id: '/shasta-vs-lake-powell'
      path: '/shasta-vs-lake-powell'
      fullPath: '/shasta-vs-lake-powell'
      preLoaderRoute: typeof ShastaVsLakePowellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shasta-lake': {
      id: '/shasta-lake'
      path: '/shasta-lake'
      fullPath: '/shasta-lake'
      preLoaderRoute: typeof ShastaLakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-shop': {
      id: '/pro-shop'
      path: '/pro-shop'
      fullPath: '/pro-shop'
      preLoaderRoute: typeof ProShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moorage': {
      id: '/moorage'
      path: '/moorage'
      fullPath: '/moorage'
      preLoaderRoute: typeof MoorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-info': {
      id: '/guest-info'
      path: '/guest-info'
      fullPath: '/guest-info'
      preLoaderRoute: typeof GuestInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploring-shasta-lake': {
      id: '/exploring-shasta-lake'
      path: '/exploring-shasta-lake'
      fullPath: '/exploring-shasta-lake'
      preLoaderRoute: typeof ExploringShastaLakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employment': {
      id: '/employment'
      path: '/employment'
      fullPath: '/employment'
      preLoaderRoute: typeof EmploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins': {
      id: '/cabins'
      path: '/cabins'
      fullPath: '/cabins'
      preLoaderRoute: typeof CabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/': {
      id: '/houseboats/'
      path: '/houseboats'
      fullPath: '/houseboats/'
      preLoaderRoute: typeof HouseboatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-boats_/$slug': {
      id: '/small-boats_/$slug'
      path: '/small-boats/$slug'
      fullPath: '/small-boats/$slug'
      preLoaderRoute: typeof SmallBoatsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/senator': {
      id: '/houseboats/senator'
      path: '/houseboats/senator'
      fullPath: '/houseboats/senator'
      preLoaderRoute: typeof HouseboatsSenatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-ii': {
      id: '/houseboats/queen-ii'
      path: '/houseboats/queen-ii'
      fullPath: '/houseboats/queen-ii'
      preLoaderRoute: typeof HouseboatsQueenIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen-i': {
      id: '/houseboats/queen-i'
      path: '/houseboats/queen-i'
      fullPath: '/houseboats/queen-i'
      preLoaderRoute: typeof HouseboatsQueenIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/queen': {
      id: '/houseboats/queen'
      path: '/houseboats/queen'
      fullPath: '/houseboats/queen'
      preLoaderRoute: typeof HouseboatsQueenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houseboats/policy': {
      id: '/houseboats/policy'
      path: '/houseboats/policy'
      fullPath: '/houseboats/policy'
      preLoaderRoute: typeof HouseboatsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/queens': {
      id: '/compare/queens'
      path: '/compare/queens'
      fullPath: '/compare/queens'
      preLoaderRoute: typeof CompareQueensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins_/policy': {
      id: '/cabins_/policy'
      path: '/cabins/policy'
      fullPath: '/cabins/policy'
      preLoaderRoute: typeof CabinsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history': {
      id: '/about/history'
      path: '/about/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof AboutHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-reviews': {
      id: '/api/public/google-reviews'
      path: '/api/public/google-reviews'
      fullPath: '/api/public/google-reviews'
      preLoaderRoute: typeof ApiPublicGoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-reviews': {
      id: '/api/public/hooks/refresh-reviews'
      path: '/api/public/hooks/refresh-reviews'
      fullPath: '/api/public/hooks/refresh-reviews'
      preLoaderRoute: typeof ApiPublicHooksRefreshReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CabinsRoute: CabinsRoute,
  ContactRoute: ContactRoute,
  DirectionsRoute: DirectionsRoute,
  EmploymentRoute: EmploymentRoute,
  ExploringShastaLakeRoute: ExploringShastaLakeRoute,
  FaqRoute: FaqRoute,
  GuestInfoRoute: GuestInfoRoute,
  MoorageRoute: MoorageRoute,
  PlanningRoute: PlanningRoute,
  ProShopRoute: ProShopRoute,
  ShastaLakeRoute: ShastaLakeRoute,
  ShastaVsLakePowellRoute: ShastaVsLakePowellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmallBoatsRoute: SmallBoatsRoute,
  AboutHistoryRoute: AboutHistoryRoute,
  CabinsPolicyRoute: CabinsPolicyRoute,
  CompareQueensRoute: CompareQueensRoute,
  HouseboatsPolicyRoute: HouseboatsPolicyRoute,
  HouseboatsQueenRoute: HouseboatsQueenRoute,
  HouseboatsQueenIRoute: HouseboatsQueenIRoute,
  HouseboatsQueenIiRoute: HouseboatsQueenIiRoute,
  HouseboatsSenatorRoute: HouseboatsSenatorRoute,
  SmallBoatsSlugRoute: SmallBoatsSlugRoute,
  HouseboatsIndexRoute: HouseboatsIndexRoute,
  ApiPublicGoogleReviewsRoute: ApiPublicGoogleReviewsRoute,
  ApiPublicHooksRefreshReviewsRoute: ApiPublicHooksRefreshReviewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
